apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: asia-southeast1-docker.pkg.dev/reiya-playground/learn-argocd/frontend
        resources:
          limits:
            memory: "100Mi"
            cpu:  "10m"
        ports:
          - containerPort: 80
